openapi: 3.0.0
servers:
  - url: https://damm.datasektionen.se
    description: Production server
  - url: http://localhost:5000
    description: Local development
info:
  description: |
    pls - Datasektionens system för att hantera behörigheter.

    Behörigheter kan vara kopplade till API-token, funktionärsposter eller individuella medlemmar.

    Auktorisera med token du får från login.
  version: 1.0.0
  title: pls
  contact:
    email: d-sys@d.kth.se
externalDocs:
  url: https://github.com/datasektionen/pls
  description: Github
